export const COMMON = {
  LOADING_END: 'LOADING_END',
  LOGOUT: 'LOGOUT',
  NO_CONNECTION: 'NO_CONNECTION',
};

export const USER = {
  LOADING: 'USER_LOADING',
  LOADING_END: 'USER_LOADING_END',
  SET_USER: 'USER_SET_USER',
};
